//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studio
    {
        public string studioName { get; set; }
        public string director { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string id { get; set; }
        public int videolibraryID { get; set; }
    
        public virtual videolibrary videolibrary { get; set; }
    }
}
