//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public string filmName { get; set; }
        public int duration { get; set; }
        public string country { get; set; }
        public int year { get; set; }
        public string plot { get; set; }
        public string audioLanguage { get; set; }
        public int rating { get; set; }
        public string actor_ref { get; set; }
        public string isHd { get; set; }
        public string hasSubtitle { get; set; }
        public string gendre { get; set; }
        public string produced_by { get; set; }
        public string type { get; set; }
        public int videolibraryID { get; set; }
    
        public virtual videolibrary videolibrary { get; set; }
    }
}
